= 部署智能合约并与之交互

与大多数软件不同，智能合约不会运行在你的电脑或是某人的服务器上：它们运行在区块链网络上。这意味着与它们交互会和传统应用有很大区别。

这个指南将会覆盖所有开始使用智能合约时需要知道的事情，包括：

 * <<local-blockchain, 建立一个本地区块链>>
 * <<getting-started-with-the-cli, 开始使用OpenZeppelin CLI>>
 * <<deploying-a-smart-contract, 部署一个智能合约>>
 * <<interacting-from-the-command-line, 使用命令行交互>>
 * <<interacting-programmatically, 使用编程方式交互>>

[[local-blockchain]]
== 建立一个本地区块链

在我们开始之前，我们首先需要一个部署合约的环境。在以太坊区块链（常称为"主网"，由"main network"而来）上需要花费真实的钱，以Ether （以太币，以太坊上原生货币）的形式。在尝试新的想法或工具时，这是一个不好的选择。

为了解决这个问题，出现了大量的“测试网络”（由"test networks"而来）：包括Ropsten, Rinkeby, 和Kovan blockchains。它们和主网非常相似，只有一点不同：你可以在这些网络上免费获得Ether，所以使用它们就不会花费你一分钱了。但是，您仍然需要管理私钥，出块时间在5到20秒范围内，以及使用免费获得的也太币。

在开发过程中，更好的选择是使用 _本地_ 区块链。它运行在你的电脑上，不需要网络接入，可以为你提供你需要的所有Ether，并且可以立刻出块。这些理由也使本地区块链非常适合 xref:writing-automated-tests.adoc#setting-up-a-testing-environment[自动化测试].

TIP: 如果你想学习如何在 _公共_ 区块链，如以太坊测试网上部署和使用合约，请查看xref:connecting-to-public-test-networks.adoc[连接到公共测试网络] 指南。

最热门的本地区块链是 https://github.com/trufflesuite/ganache-cli[Ganache]。想要为你的项目下载它，运行以下命令：

```console
$ npm install --save-dev ganache-cli
```

启动时，Ganache将创建随机的一组解锁帐户，并为其分配以太币。想要得到与本指南中将使用的地址相同的地址，可以在deterministic模式下启动Ganache：

```console
$ npx ganache-cli --deterministic
```

Ganache将输出可用的帐户及其私钥的列表，以及一些区块链配置值。最重要的是，它将显示其（节点）的地址，我们将使用这个地址来连接到它。默认情况下，该值为127.0.0.1:8545。

需要记住的是，每次运行Ganache时，都会创建一个全新的本地区块链——先前的运行状态**不**会被保留。这对于短暂的实验来说很好，但这意味着在学习本指南的过程中，你都需要打开一个运行Ganache的窗口。或者，你可以使用 `--db` 选项运行Ganache，提供一个在两次运行之间存储其数据目录。

NOTE: 作为对Ganache的替换，你可以在 _https://geth.ethereum.org/getting-started/dev-mode[开发] https://wiki.parity.io/Private-development-chain[模块]_ 运行一个真实的以太坊节点。它的设置有点复杂，测试和开发不够灵活，但是比Ganache更能代表实际网络。

[[getting-started-with-the-cli]]
== 开始使用OpenZeppelin CLI

这里包含了智能合约部署和交互的底层细节，但是你不用太过担心： xref:cli::index.adoc[*OpenZeppelin 命令行接口 (CLI)*] 将会为你注意到这些环节。

你应该已经在 xref:developing-smart-contracts.adoc#compiling-solidity-source-code[编译智能合约] 中使用过了CLI，如果没有的话，现在下载它：

```console
$ npm install --save-dev @openzeppelin/cli
```

为了管理你已经发布的合约，你需要创建一个新的CLI项目。现在就做吧，并且在出现提示时为其提供项目名称和版本号：

```console
$ npx openzeppelin init
```

NOTE: 你可以称OpenZeppelin CLI为 `openzeppelin` 或者 `oz`。为了准确，下文我们将使用后者。

在初始化时会发生两件事情。首先，将会创建一个名为 `.openzeppelin` 的目录，用来存储关于项目的信息。这个目录将会被CLI管理：你不需要手动的编辑任何文件。你应当把 xref:cli::configuration.adoc#configuration-files-in-version-control[其中的一些文件] 提交给Git。

其次，CLI将会在 `networks.js` 文件中存储网络配置。为了方便起见，配置文件中已经设置了 `development` 这一项，并配置了匹配 <<local-blockchain, Ganache>> 的默认值。

来试试我们的第一个CLI命令并熟悉它。我们将会从查询Ganache的所有未锁定帐户开始：

```console
$ npx oz accounts
```

与 `init` 和 `compile` 命令不同， `accounts` 命令需要在网络上运行：CLI将列出 `networks.js` 文件中的选项，并提示你选择一个。

当你选择了Ganache的 `development` 选项，它将会输出所有可用的账户：

```console
$ npx oz accounts
? Pick a network development
Accounts for dev-1576250059363:
Default: 0x90F8bf6A479f320ead074411a4B0e7944Ea8c9C1
All:
- 0: 0x90F8bf6A479f320ead074411a4B0e7944Ea8c9C1
- 1: 0xFFcf8FDEE72ac11b5c542428B35EEF5769C409f0
...
```

我们也可用通过 `balance` 命令查询这些账户的余额：

```console
$ npx oz balance
? Enter an address to query its balance 0x90F8bf6A479f320ead074411a4B0e7944Ea8c9C1
? Pick a network development
Balance: 100 ETH
```

这就体现了使用本地区块链的便利之处：Ganache给我们所有的账户预存了100Ether，这意味着我们可以发送大量的交易！

[[deploying-a-smart-contract]]
== 部署一个智能合约

学过了 <<getting-started-with-the-cli, 初始化CLI>>， 我们现在可以部署合约了。我们将要部署在 xref:developing-smart-contracts.adoc#setting-up-a-solidity-project[编写智能合约] 指南中提到的 `Box` 合约。记得要保存一份 `contracts/Box.sol`：

[[box-contract]]
```solidity
// contracts/Box.sol
// SPDX-License-Identifier: MIT
pragma solidity ^0.6.0;


contract Box {
    uint256 private value;

    // 当存储的值发生变化时触发该事件
    event ValueChanged(uint256 newValue);

    // 在合约中存入一个新的值
    function store(uint256 newValue) public {
        value = newValue;
        emit ValueChanged(newValue);
    }

    // 读取最新的值
    function retrieve() public view returns (uint256) {
        return value;
    }
}
```

OpenZeppelin CLI将会指导你完成部署过程，询问需要的信息。使用 `deploy` 命令，将 `Box` 合约部署在 `development` 网络上 (<<local-blockchain, Ganache>>)。在提示部署类型时选择常规（regular）：

```console
$ npx oz deploy
✓ Compiled contracts with solc 0.6.7 (commit.b8d736ae)
? Choose the kind of deployment regular
? Pick a network development
? Pick a contract to deploy Box
✓ Deployed instance of Box
0xe78A0F7E598Cc8b0Bb87894B0F60dD2a88d6a8Ab
```

完成了！在实际的网络上这一步需要花费一些时间，但在本地区块链上立刻就完成了。

TIP: 如果报错connection error, 确保你在另一个终端 <<local-blockchain, 运行Ganache>>。

CLI将跟踪你已经部署的合约，同时也会在部署后显示其地址（在我们的例子里，地址是 `0xe78A0F7E598Cc8b0Bb87894B0F60dD2a88d6a8Ab`）。这个值将在我们想要通过编程方式与它交互时派上用场。

NOTE: 请记住，本地区块链 **不会** 在多次运行中保持它的状态！如果关闭Ganache进程，那么就必须重新部署合约。

[[interacting-from-the-command-line]]
== 使用命令行交互

在 <<deploying-a-smart-contract, 部署>> 了我们的 `Box` 合约后，我们可以通过 <<getting-started-with-the-cli, CLI>> 来使用它了。

=== 发送交易

`Box` 合约的第一个方法，`store`，获取一个整数类型的变量然后把它存入合约存储中。因为这个方法 _改变_ 了区块链的状态，所以我们需要向合约 _发布一个交易_ 来执行它。

发布交易可以通过CLI的 `send-tx` 命令实现。在CLI提示时，选择 `Box` 合约，选择  `store` 方法，然后选择要发送给它的值：

```console
$ npx oz send-tx
? Pick a network development
? Pick an instance Box at 0xe78A0F7E598Cc8b0Bb87894B0F60dD2a88d6a8Ab
? Select which function store(newValue: uint256)
? newValue: uint256: 5
✓ Transaction successful. Transaction hash: 0xd40664c0a80215e964975ab3cea7f27a453c802f01c15cd754aca2c7bd6bd6c1
Events emitted:
 - ValueChanged(5)
```

请留意， `send-tx` 是如何检测到 `Box` 发出了一个 `ValueChanged` 事件并包含了我们新存入的值。

=== 查询状态

`Box` 的另一个方法为 `retrieve`，它返回存储在合约中的整型变量值。这是一个关于区块链状态的 _查询_ ，所以我们不需要发布交易：使用静态的 _call_ 就足够了。

你可能注意到了 `send-tx` 的可调用的方法列表中没有包含 `retrieve` ：这是因为查询是使用 `call` 命令执行的：

```console
$ npx oz call
? Pick a network development
? Pick an instance Box at 0xe78A0F7E598Cc8b0Bb87894B0F60dD2a88d6a8Ab
? Select which function retrieve()
✓ Method 'retrieve()' returned: 5
5
```

因为 `call` 不会发布一个交易，所以不会返回交易的哈希值。这也意味着使用 `call` 不会花费以太币，在任何网络上都是免费的。

TIP: 想要了解更多关于 `send-tx` 和 `call` 的内容，可用查看 xref:cli::commands.adoc[CLI API参考]。

[[interacting-programmatically]]
== 使用编程方式交互

命令行对于原型化和运行一次性的命令很有用。但是，最终你将希望从自己的应用程序中与合约进行交互，这意味着需要以编程的方式调用或发送交易。

在本节中，我们将要学习如何使用JavaScript的 https://web3js.readthedocs.io/en/1.2.4/[web3.js] 来与我们的合约交互，并且使用 xref:contract-loader::index.adoc[*OpenZeppelin合约装载器（OpenZeppelin Contract Loader）*] 来加载它们：

[source,console]
----
$ npm install web3 @openzeppelin/contract-loader
----

TIP: 要记住的是，还有许多其他JavaScript库可用，你可以使用喜欢的任何一个。合约一旦部署，你就可以通过任何库与之交互！

[[connecting-to-the-network]]
=== 连接到网络

让我们开始在一个新的 `src/index.js` 文件中进行编写代码，在此我们将编写JavaScript脚本，首先是一些用于加载库和 https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/async_function[编写 async代码] 的模板。

[source,js]
----
// src/index.js
const Web3 = require('web3');
const { setupLoader } = require('@openzeppelin/contract-loader');

async function main() {
  // 我们的代码写在这里
}

main();
----

我们将首先初始化一个新的 `web3` 实例。这个对象连接了区块链节点，并允许我们发送交易和查询。我们将创建一个连接到我们之前启动的 <<local-blockchain,本地开发网络>>，该网络运行在localhost的8545端口上。

我们可以通过向本地节点查询一些信息（例如已启用的帐户列表）来测试连接是否有效：

[source,js]
----
// 建立web3对象, 连接到本地开发网络
const web3 = new Web3('http://localhost:8545');

// 从本地节点拿到账户
const accounts = await web3.eth.getAccounts();
console.log(accounts);
----

NOTE: 我们不会在每个代码片段上都重复模板代码，所以请保证在我们上面定义的 `main` 函数 _内_ 进行编码!

使用 `node` 命令运行上面的代码，并且检查你获得的可用账户列表。

[source,console]
----
$ node src/index.js
[ '0x90F8bf6A479f320ead074411a4B0e7944Ea8c9C1',
  '0xFFcf8FDEE72ac11b5c542428B35EEF5769C409f0',
  ... ]
----

这些账户应当和你之前运行 `oz accounts` 命令得到的账户一致。现在我们有了第一个用于从区块链中获取数据的代码段，让我们开始研究合约。

[[getting-a-contract-instance]]
=== 获得一个合约实例

为了与 <<box-contract,`Box`>> 合约进行交互，我们将使用 xref:contract-loader::index.adoc[*OpenZeppelin合约装载器*] 来创建一个新的 https://web3js.readthedocs.io/en/v1.2.7/web3-eth-contract.html[web3合约实例]。

一个web3合约实例是一个JavaScript对象，它代表了我们在区块链上的合约，我们可以使用它与合约进行交互。要创建一个合约实例，我们需要给合约装载器提供合约名称和地址，地址是我们运行 `oz create` 命令返回的值。

[source,js]
----
// 建立web3对象，连接到本地开发网络和合约装载
const web3 = new Web3('http://localhost:8545');
const loader = setupLoader({ provider: web3 }).web3;

// 使用合约装载器建立一个web3合约，代表我们发布Box实例
const address = '0xe78A0F7E598Cc8b0Bb87894B0F60dD2a88d6a8Ab';
const box = loader.fromArtifact('Box', address);
----

NOTE: 请确保将 `address` 替换为部署合约时获得的地址，你的地址可能与例子中的地址不同。

我们现在可以使用这个JavaScript对象来与合约交互了。

[[calling-the-contract]]
=== 调用合约

让我们以显示 `Box` 合约目前的值开始。我们需要使用 https://web3js.readthedocs.io/en/1.0/web3-eth-contract.html#methods-mymethod-call[call] 方法调用合约的公有方法 `retrieve()` ，使用 https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/await[await] 获取返回值：

[source,js]
----
// 调用已经发布的Box合约的retrieve()方法
const value = await box.methods.retrieve().call();
console.log("Box value is", value);
----

这段代码的效果与我们之前使用的CLI命令 `oz call` 是一样的。现在确保所有代码能够很好的运行，再一次运行脚本并且查看输出的值：

[source,console]
----
$ node src/index.js
Box value is 5
----

[WARNING]
====
如果你重启过ganache，那么脚本可能会运行失败。重启ganache会清除本地区块链的所有状态，所以 `Box` 合约可能不在原来的地址了。

如果发生了这样的事，那么 <<local-blockchain, 启动ganache>> 再 <<deploying-a-smart-contract, 重新部署>> `Box` 合约。
====

[[sending-a-transaction]]
=== 发布交易

我们现在要向我们的Box https://web3js.readthedocs.io/en/v1.2.7/web3-eth-contract.html#methods-mymethod-send[发布一个交易] 来 `store` 一个新的值。要记住的是，发布一个交易不像进行一次调用那么直接：我们需要搞清楚交易的sender，gas limit，和我们要使用的gas price。为了让这个例子更简单，我们将会使用一个硬编码的gas和gas price，并且使用node中的第一个可用的账户来发布交易。


NOTE: 在实际应用中，你可能需要 https://web3js.readthedocs.io/en/v1.2.7/web3-eth-contract.html#methods-mymethod-estimategas[估计交易的gas] ，并且查看  https://ethgasstation.info/[gas price oracle] 来获取每个交易最优的gas price值。

让我们将 `20` 这个值存入 `Box` 合约中，然后使用我们之前写的代码来将这个更新的值显示出来：

[source,js]
----
// 从本地node获取账户，我们将会使用第一个账户来发布交易
const accounts = await web3.eth.getAccounts();

// 发布一个交易来给Box合约store()一个新的值
await box.methods.store(20)
  .send({ from: accounts[0], gas: 50000, gasPrice: 1e6 });

// 调用Box合约的retrieve()方法
const value = await box.methods.retrieve().call();
console.log("Box value is", value);
----

我们现在可以运行这段代码，然后发现box合约的值已经更新了！

[source,console]
----
$ node src/index.js
Box value is 20
----

== 下一步

现在你知道了如何用手动方式和编程方式来建立一个本地区块链，发布合约和与合约交互。你将要学习测试环境，公共测试网络和实际应用的知识：

* xref:writing-automated-tests.adoc[编写自动化测试]
* xref:connecting-to-public-test-networks.adoc[连接到公共测试网络]
* xref:preparing-for-mainnet.adoc[准备主网]
