= 创建一个Node项目

新软件产业通常始于每个项目共享相同的技术栈。以太坊生态系统也不例外，它选择的语言是 https://en.wikipedia.org/wiki/JavaScript[JavaScript] 。包括OpenZeppelin软件在内的所有最常用的以太坊库都是用JavaScript或其变体编写的。

传统上，JavaScript代码是作为网站的一部分在Web浏览器上运行的，但也可以使用 https://nodejs.org[Node] 作为独立的进程执行。

这篇指南将会帮助你配置Node开发环境，你在使用不同的OpenZeppelin工具和第三方产品时将会用到这个环境。

TIP: 如果你已经对Node，npm和Git非常熟悉了，那么就直接跳过这篇指南吧！

== 下载Node

在你的电脑上获取Node的方法有很多种：你可以通过 https://nodejs.org/en/download/package-manager/[包管理工具] 或者直接下载 https://nodejs.org/en/download/[安装程序] 。

完成这些后，在终端运行 `node --version` 来检查你的安装：10.x或12.x系列的任何版本都与大多数以太坊软件兼容。

```console
$ node --version
v10.16.3
```

== 创建npm包

JavaScript软件通常与 _packages_ 相关， https://www.npmjs.com/[npm注册表]。一个包就是一个简单的文件夹，它包含了一个叫做 `package.json` 的文件，描述了包的名字，版本，内容和其他信息。

当你开发你自己的项目时就会用到Node的所有安装，包括包含npm注册表的命令行客户端。开始一个新的项目，你只需要创建一个文件夹然后运行：

```console
$ npm init
```

就是这么简单！你已经新建的 `package.json` 文件将会随着项目的进展而扩展，就比如你使用 `npm install` 来下载依赖的时候。

TIP: JavaScript和npm是世界上最常用的软件工具：如果您有疑问，可以在网上找到很多有关它们的信息。

[[using-npx]]
=== 使用 `npx`

npm注册表中存储了两种广义的软件包： _libraries_ 和 _executables_。已安装的库的用法与其他JavaScript代码一样，但是可执行文件是特殊的。

当下载node时会包含第三方库： https://blog.npmjs.org/post/162869356040/introducing-npx-an-npm-package-runner[`npx`]。它会用于运行项目内安装的可执行文件。

一些OpenZeppelin工具（例如 xref:cli::index.adoc[CLI]）只有在使用 `npx` 时才可以运行。不包含 `npx` 时将会导致错误，因为命令没有包含在系统的环境变量中，所以为了更明确，我们将会在指南中展示完整的命令：

```console
$ openzeppelin init
openzeppelin: command not found
$ npx openzeppelin init
Welcome to the OpenZeppelin SDK!
```

WARNING: 运行 `npx` 时，请确保您在项目目录中！否则，它将只是为了运行该命令而再次下载完整的可执行文件，这很可能 _不_ 是您想要的。

== 使用版本控制跟踪

在开始编写代码之前，您应该添加为项目添加 https://en.wikipedia.org/wiki/Version_control[版本控制软件] 来跟踪变化。

目前，使用最多的工具是 https://git-scm.com[Git]，通常与 https://github.com[GitHub] 一起使用以进行托管。实际上，你可以在我们的 https://github.com/OpenZeppelin[GitHub 仓库] 中找到所有OpenZeppelin软件的完整源代码和历史。

TIP: 如果你之前没有使用过Git，可以从 https://guides.github.com/introduction/git-handbook/[Git Handbook] 开始。
