= 编写智能合约自动化测试

在区块链环境中，一个错误可能花费掉你所有的资金——甚至更糟，它会花费掉你用户的资金！这个指南将会帮助你开发健壮的应用程序，通过编写自动化测试来检测应用是不是像你预期的那样运行。

我们接下来将会讨论以下话题：

 * <<setting-up-a-testing-environment, 配置测试环境>>
 * <<writing-unit-tests, 编写单元测试>>
 * <<performing-complex-assertions, 执行复杂的命令>>

=== 关于测试

测试技术有很多种，从 xref:deploying-and-interacting.adoc#interacting-from-the-command-line[简单的手动验证] 到复杂的端到端设置，每种方式都有它们的用处。

当涉及到智能合约开发时，经验表明对合约的 https://en.wikipedia.org/wiki/Unit_testing[_单元测试_] 是值得期待的。这些测试都很容易编写，并且运行很快，同时你可以很容易地给代码增加特征或是修改漏洞。

智能合约单元测试包括多种小规模的针对性测试，它们可以检查合约中每一个小部分的正确性。可以使用单独的句子将测试规范表达出来，例如“管理员可以暂停合约”，“转移代币会触发事件”或者“非管理员不能挖矿获得新币”。

[[setting-up-a-testing-environment]]
== 配置测试环境

因为智能合约必须要在区块链上执行，所以你也许想知道我们将要 _怎样_ 运行这些测试用例。使用实际的以太坊网络费用很高，测试网络是免费的，但它很慢（出块时间在5到20秒之间）。如果我们想要在每一次修改代码后运行成百上千个测试用例，那么我们还需要找到更适合的测试网络。

我们将要使用的就是 _本地区块链_ ：它是一个以太坊真实版本的精简版，运行在你的电脑上，并且没有与互联网连接。这将简化很多事情：你不需要获取以太币，也能很快挖出新块。

为了帮助我们测试，我们将会使用 xref:test-environment::index.adoc[*OpenZeppelin测试环境*]，它是一个JavaScript库，可以帮助我们设置本地区块链。

NOTE: 如果你已经阅读了 xref:deploying-and-interacting.adoc#local-blockchain[部署和交互]，你应该已经熟悉了 https://github.com/trufflesuite/ganache-cli/[Ganache]。这就是测试环境在底层的用处，它可以帮助你管理配置。

下载OpenZeppelin测试环境，运行以下命令：

```console
$ npm install --save-dev @openzeppelin/test-environment
```

一旦你 `require` 了自己的JavaScript代码库，它将会自动运行一个本地测试链。它将会输出一个账户列表，列表中的账户都预先充值了Ether。还会列出通过编译后的文件和通过其他帮助工具（函数）来加载合约的简便方法。

```javascript
const { accounts, contract } = require('@openzeppelin/test-environment');

// 使用不同解锁且有资产的账户
const [ admin, deployer, user ] = accounts;

// 使用artifact创建一个合约对象
const MyContract = contract.fromArtifact('MyContract');
```

如果你想要更加详细的了解输出的值和它们的用处，那么可以查看测试环境的 xref:test-environment::api.adoc[API参考].

[[writing-unit-tests]]
== 编写单元测试

为了实际运行你的测试实例，你需要下载JavaScript的 _test runner_。你可以使用 xref:test-environment::choosing-a-test-runner.adoc[推荐列表] 中的任何一个：在本指南中，我们将选择 https://mochajs.org/[Mocha] 和 https://www.chaijs.com/[Chai]。

```console
$ npm install --save-dev mocha chai
```

新建一个 `test` 目录：用来存放你的测试文件。最好的构建这些文件的方法就是通过镜像 xref:developing-smart-contracts.adoc#setting-up-a-solidity-project[`contracts`目录]：对 `contracts` 目录中的每一个 `.sol` 文件，都创建一个对应的 `.test.js` 文件。

现在到了编写我们第一个测试的时候了！我们将会测试 xref:developing-smart-contracts.adoc#box-contract[前面指南中出现的] `Box` 合约的属性：这个合约使你可以 `获取` 合约所有者预先 `存储` 在变量中的值。

```javascript
// test/Box.test.js

// 加载依赖
const { accounts, contract } = require('@openzeppelin/test-environment');
const { expect } = require('chai');

// 加载已编译的artifacts
const Box = contract.fromArtifact('Box');

// 开始测试模块
describe('Box', function () {
  const [ owner ] = accounts;

  beforeEach(async function () {
    // 为每个测试部署一个新的Box合约
    this.contract = await Box.new({ from: owner });
  });

  // 测试用例
  it('retrieve returns a value previously stored', async function () {
    // 存储一个值——记得只有所有者账户才能执行此操作！
    await this.contract.store(42, { from: owner });

    // 如果返回值是相同的就进行测试
    // 注意我们需要使用字符串的格式与256位int类型做比较
    expect((await this.contract.retrieve()).toString()).to.equal('42');
  });
});
```

TIP: 很多书籍都写过如何将单元测试结构化：想要获取此类参考，可以查看 https://github.com/OpenZeppelin/openzeppelin-contracts/tree/master/test[OpenZeppelin合约的测试]，或者接下来的 https://medium.com/coinmonks/how-to-test-ethereum-smart-contracts-ac28fa852281[ERC20测试指南].

现在我们准备好运行测试了！最好的方式就是给 `package.json` 添加一个 `test` 脚本：

[source,diff]
----
 "scripts": {
+  "test": "mocha --exit --recursive test"
 }
----

有了这个脚本，运行 `npm test` 命令就可以执行 `test` 目录下所有的测试了，这样就可以检查合约是否按照我们希望的那样运行：

```console
$ npm test
  Box
    ✓ retrieve returns a value previously stored
```

[TIP]
====
如果你修改了合约，别忘了要重新编译！如果你希望在每个测试之前自动重新编译，那么可以将 `test` 脚本设置为：

`oz compile && mocha --exit --recursive test`
====

测试环境的默认值是可以修改的，默认的参数适用于大多数场景，但是你也可以 xref:test-environment::getting-started.adoc#configuration[设置] 参数来让它提供更多的账户，或者使用不同种类的合约对象。

同时，也可以设置持续集成服务，例如 https://circleci.com/[CircleCI]。这样可以在你每次提交代码到GitHub后自动运行测试。

[[performing-complex-assertions]]
== 执行复杂命令

合约中很多有趣的属性很难获取到，例如：

 * 验证合约是否因错误导致回滚
 * 判断一个账户的以太币余额变化了多少
 * 检查是否触发了正确的事件

xref:test-helpers::index.adoc[*OpenZeppelin 测试助手*] 是一个可以帮助你测试这些属性的库。它将会简化在区块链上模拟时间的任务，同时它也可以处理大量任务。

```console
$ npm install --save-dev @openzeppelin/test-helpers
```

```javascript
// test/Box.test.js

const { accounts, contract } = require('@openzeppelin/test-environment');
const { expect } = require('chai');

// 从测试帮助导入实体
const { BN, expectEvent, expectRevert } = require('@openzeppelin/test-helpers');

const Box = contract.fromArtifact('Box');

describe('Box', function () {
  const [ owner, other ] = accounts;

  // 使用大整数 ('big numbers')
  const value = new BN('42');

  beforeEach(async function () {
    this.contract = await Box.new({ from: owner });
  });

  it('retrieve returns a value previously stored', async function () {
    await this.contract.store(value, { from: owner });

    // 使用大整数比较
    expect(await this.contract.retrieve()).to.be.bignumber.equal(value);
  });

  it('store emits an event', async function () {
    const receipt = await this.contract.store(value, { from: owner });

    // 测试新的值将会触发一个ValueChanged事件
    expectEvent(receipt, 'ValueChanged', { newValue: value });
  });
  
  it('non owner cannot store a value', async function () {
    // 测试交易回滚
    await expectRevert(
      this.contract.store(value, { from: other }),
      'Ownable: caller is not the owner'
    );
  });
});
```

不需要任何配置：测试环境将会发现测试助手然后帮助你完成复杂的工作。

这些将测试 xref:developing-smart-contracts.adoc#using-openzeppelin-contracts[先前的指南中的]  `Box` 合约的属性：这是一个简单的合约，可以 `检索` 所有者先前 `存储` 的值。

再次运行你的测试就可以看到测试助手正在运行：

```console
$ npm test
  Box
    ✓ retrieve returns a value previously stored
    ✓ store emits an event
    ✓ non owner cannot store a value
```

测试助手将会帮助你编写有效的命令，这样你就不用担心以太坊库中的底层细节。想要知道它还有什么用处，可以查看它的 xref:test-helpers::api.adoc[API参考]。

TIP: 使用测试助手不需要OpenZeppelin测试环境：要了解如何独立使用它们或将其集成到其他系统中，可以参考 xref:test-helpers::configuration.adoc[文档]。

== 下一步

一旦对合约进行了全面的测试并确定了合约的正确性，接下来就需要将其部署到真实的网络并开始与它们进行交互。以下指南可帮助你快速掌握这些问题：

 * xref:connecting-to-public-test-networks.adoc[连接到公共测试网络]
 * xref:deploying-and-interacting.adoc[开发和交互]
 * xref:preparing-for-mainnet.adoc[准备主网]
